0x00-python-hello_world

diff --git a/0x00-python-hello_world/101-compile b/0x00-python-hello_world/101-compile
--- a/0x00-python-hello_world/101-compile
+++ b/0x00-python-hello_world/101-compile
@@ -1,13 +1,18 @@
 #!/bin/bash
 if [ -z "$PYFILE" ]; then
-  echo "PYFILE environment variable is not set."
-  exit 1
+    echo "PYFILE environment variable is not set."
+    exit 1
 fi
-echo "Compiling $PYFILE ..."
-python3 -m compileall -b -o "./" "$PYFILE"
-if [ $? -eq 0 ]; then
-  mv "${PYFILE}__pycache__/${PYFILE%.py}.cpython-38.pyc" "${PYFILE%.py}.pyc"
-  echo "Compilation successful."
-else
-  echo "Compilation failed."
+if [ ! -f "$PYFILE" ]; then
+    echo "File '$PYFILE' does not exist."
+    exit 1
 fi
+filename=$(basename -- "$PYFILE")
+filename="${filename%.*}"
+python3 -m compileall "$PYFILE"
+if [ $? -ne 0 ]; then
+    echo "Compilation failed."
+    exit 1
+fi
+mv "$PYFILE" "${PYFILE}c"
+echo "Compilation successful. Output file: ${PYFILE}c"
